# Generated by Django 6.0.1 on 2026-01-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_albumtemplate_album_photo_album_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='albums.albumpage'),
        ),
    ]
