# Generated by Django 6.0.1 on 2026-01-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_photo_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumtemplate',
            name='template_type',
        ),
        migrations.AlterField(
            model_name='albumtemplate',
            name='css_styles',
            field=models.TextField(default='', help_text='CSS, который будет применяться к страницам альбома'),
        ),
        migrations.AlterField(
            model_name='albumtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='albumtemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Мини-превью шаблона (например, маленькая картинка для выбора)', null=True, upload_to='templates/'),
        ),
    ]
