# Generated by Django 6.0.1 on 2026-01-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_albumtemplate_template_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumpage',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='albumpage',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='albumpage',
            name='title',
        ),
        migrations.AddField(
            model_name='albumpage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='albums.albumtemplate'),
        ),
        migrations.AddField(
            model_name='albumpage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='album_pages/thumbnails/'),
        ),
    ]
