# Generated by Django 6.0.1 on 2026-01-19 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
