# Generated by Django 6.0.1 on 2026-01-19 17:26

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=albums.models.collage_directory_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, upload_to=albums.models.photo_directory_path),
        ),
    ]
