# Generated by Django 6.0.1 on 2026-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_collage_image_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
